rapidsai/libgdf

python/libgdf_cffi/__init__.py
The local path prefix (e.g. `./`) is taken more strictly on Linux than OSX.  As a result, it prevents looking into the conda environment for the `libgdf.so`.
The problem is not affecting osx.
=> Fix library not found on linux

include/gdf/cffi/functions.h, python/tests/test_joining.py, src/joining.cu
to return left and right indices in their own contiguous sequences.
This is more efficient for consumption.
=> Shuffle join result

python/tests/test_reductions.py, python/tests/test_unaryops.py, python/tests/utils.py, src/reductions.cu
* rng for tests is updated to give negative floats.
* error tolerance is increased for some tests.
=> Fix incorrect identity value for max-reduce

include/gdf/cffi/types.h
PR #47 broke the build due to error with cffi.  This patch fixes it.
=> Fix build. Ensure struct gdf_dtype_extra_info is C compatible

src/hash-join/join_compute_api.h
There was an error in how the capacity for the hash table was computed that would cause an integer overflow for large enough input sizes.
=> Fix integer overflow in concurrent_unordered_multimap size calculation

README.md, conda-recipes/libgdf/meta.yaml, conda_environments/dev_py35.yml
Since users are often either running in a Docker container with CUDA already installed, or have CUDA already installed on their machine, we shouldn't have the cudatoolkit conda package as a dependency for the conda install.
WIP to update the README to instruct users that the CUDA toolkit is required and basic instructions on how to install it from either conda or standard NVIDIA channels.
=> [REVIEW] Remove cudatoolkit from conda dependency

include/sqls_rtti_comp.hpp, src/sqls_ops.cu, src/tests/sqls/sqls_g_tester.cu
Specifically: initializing dummy variables to zero; removing meaningless const type qualifiers; adding missing return statements; removing `__device__` specifier on function that passes `cout` to a thrust function. 
Note: warnings caused by ModernGPU using shfl rather than shfl_sync persist. This is being handled separately.
=> [REVIEW] Fix warnings in sqls CUDA files

src/streamcompactionops.cu
1. Shouldn't subtract unsigned types and then compare to zero. Changed the code to just compare the two values rather than subtracting them.
2. Removed a defined-but-never-used variable.
=> [REVIEW] Fixed trivial warnings in streamcompactionops.cu

src/gdf_table.cuh, src/groupby/groupby.cuh, src/hashmap/concurrent_unordered_multimap.cuh, src/hashmap/hash_functions.cuh, src/join/hash/join_compute_api.h, src/join/hash/join_kernels.cuh, src/join/joining.cu, src/join/joining.h, src/sqls_ops.cu, src/tests/hash_map/multimap-test.cu, src/tests/join/join-tests.cu
- Added gdf_table which inherits from managed class to be allocated with managed memory.
- Implemented a hash_combine function to combine two hash values.
- Refactored the join_hash function to operate on gdf_tables.
- Eliminated the InnerJoin and LeftJoin functions in favor of a single compute_hash_join function. Refactored the API to operate on gdf_tables.
- Added size_type as a template parameter to unordered_multimap.
- Updated the signature of the probe_hash_table function to work with new gdf_table structure.
- Added commented to probe_hash_table_uniq_keys kernel to indicate that it still needs to be updated to work with an arbitrary number of columns.
- Added date and timestamps for joins.
=> Hash Join for arbitrary number of columns

.travis.yml
This should fix the errors we are seeing in Travis CI where builds fail due to `unknown package libboost-all-dev`
Notes:
* Also moving `libboost-all-dev` install to `before_install` as recommended by Travis CI docs
=> [REVIEW] FIX Update Travis CI Script to Update apt Before libboost Install

CMakeLists.txt
`pytest-ci` option was intended to produce a `junit.xml` file for gpuCI to consume; however, it did not work. Instead of leaving this dead code in the `CMakeLists.txt` I'm removing it.
For gpuCI I am calling `py.test` directly with the flags needed to generate the file in an accessible place to report the results.
Same as #104 but rebased.
=> [REVIEW] Remove pytest-ci option from CMakeLists.txt

CMakeLists.txt, include/sqls_rtti_comp.hpp, src/hashmap/concurrent_unordered_map.cuh, src/hashmap/concurrent_unordered_multimap.cuh, src/ipc.cu, src/sqls_ops.cu, src/streamcompactionops.cu, src/tests/filterops_numeric/helper/utils.cu, src/tests/filterops_numeric/helper/utils.cuh, src/tests/filterops_numeric/test_example.cu, src/tests/groupby/groupby-gdf-test.cu, src/tests/groupby/groupby-kernels-test.cu, src/tests/hash_map/map-test.cu, src/tests/hash_map/multimap-test.cu, src/tests/hashing/hash-test.cu, src/tests/quantiles/quant_tester.cu, src/tests/sqls/sqls_g_tester.cu, src/tests/unaryops/unaryops-test.cu
- Enables the following compiler settings:
For .cpp files: `-Werror`: treat warnings as errors
For .cu files: `-Xcompiler -Wall,-Werror`: all warnings; treat warnings as errors, and
`-Wno-deprecated-declarations; -Xptxas --disable-warnings`: Hide warnings for deprecated shfl functions used in modern GPU (to be removed once MGPU is removed from the code or fixed).
- Also fixes all current warnings (mostly in gtests) to ensure libgdb compiles with -Werror. Note that this also fixes #115.
=> [REVIEW] Enable warnings as errors

CMakeLists.txt, src/tests/groupby/groupby-kernels-test.cu
I missed this flag in the now-merged #117 
This flag makes calling a __host__ function from a __device__ function an error rather than a warning.
Please merge ASAP.
=> Add NVCC flag "-Werror cross-cross-execution-space-call" 

src/sqls_ops.cu
This PR fixes the libgdf groupby call so that it will not return an error when an empty dataframe is passed in. Instead, it returns GDF_SUCCESS and ensures the outputs are set to empty.
=> [REVIEW] Allow empty inputs for GroupBy

python/tests/test_errorhandling.py, src/binaryops.cu, src/unaryops.cu
Currently both binary ops and unary ops will error out if the input size is 0. This PR fixes it to check if the inputs are empty, and return immediately with GDF_SUCCESS if they are.
=> [REVIEW] Fixes binary ops and unary ops to return immediately if input is empty

src/join/hash/join_compute_api.h
…incorrect type. This resolves https://github.com/gpuopenanalytics/libgdf/issues/127.
This fixes https://github.com/gpuopenanalytics/libgdf/issues/127
The multimap class's template parameter for the `unused_value` was being set incorrectly to use the `size_type` instead of the value type `output_index_type`.
=> [REVIEW] Fixes truncation warning in multimap template parameters

.travis.yml, travisci/upload.sh
Since CUDA 9.0 builds are forward compatible, but CUDA 9.2 builds aren't necessarily backwards compatible, should only publish CUDA 9.0 builds.
=> [REVIEW] Only build CFFI on CUDA 9.0, only upload to Anaconda for CUDA 9.0

include/gdf/errorutils.h, include/gdf/utils.h, src/gdf_table.cuh, src/join/hash/join_kernels.cuh, src/tests/join/join-tests.cu, src/tests/join/valid_vectors.h, src/util/bit_util.cuh
Due to tight time deadlines, this PR finishes what was started by @aocsa in https://github.com/gpuopenanalytics/libgdf/pull/124
Many thanks to @aocsa for all the work he already did that made my work that much easier.
By definition, `NULL != x ∀ x`, therefore, it is impossible for a row with a single `NULL` value to be equal to any other row. As a result, we introduce the concept of a row validity bit-mask that indicates if a row in the table contains even a single `NULL`, in which case the entire row is considered to be invalid. 
The row validity bitmask is constructed by `AND`ing all of the constituent `gdf_column` validity bitmasks together.  This is done in the `gdf_table` constructor.
A new function `gdf_table::is_row_valid(size_type row_index)` was introduced which returns the state …
=> [REVIEW] Finalizes hash-join NULL support

src/gdf_table.cuh
Implemented a kernel to also scatter the bits in the validity bitmasks when the elements of the columns are permuted in the `gdf_hash_partition` function.
=> [REVIEW] Scatter validity bitmask in gdf-hash_partition

src/hashmap/concurrent_unordered_map.cuh
Added explicit casts to the value 1 in the atomicAdd that is used for the Count aggregator. 
Without this, there seems to be a compiler error reported by some users.
=> [REVIEW] Explicit cast for atomicAdd operand

src/tests/validops/valids-tests.cu, src/validops.cu
This function improves the performance of gdf_count_nonzero_mask by using a custom kernel instead of using thrust's transform reduction, which incurred surprising overheads due to cudaFuncGetAttributes.
=> [REVIEW] Optimize gdf_count_nonzero_mask

src/join/hash/join_compute_api.h
The buffers for the Join output are allocated in a loop because we may not know the exact size of the output and may need to reallocate the buffers and try again. 
However, in the case that we need to try again, we weren't freeing the previous buffers, which would result in a memory leak. 
This PR fixes the issue by freeing the memory if we need to double the buffer size and try again.
=> [REVIEW] Resolved potential memory leak in hash Joins 

cmake/Modules/ConfigureGoogleTest.cmake, cmake/Modules/FindArrow.cmake
When looking for `arrow.pc`, it is assumed that `${ARROW_ROOT}/lib` is the path containing the arrow library. This PR ensures that `arrow.pc` is found even if the library is in a location such as `${ARROW_ROOT}/lib64` or `${ARROW_ROOT}/lib/x86_64-linux-gnu`.
Similarly, the directories for finding GTest libraries is expanded to include `{GTEST_ROOT}/lib/x86_64-linux-gnu` and `${GTEST_ROOT}/lib64`.
=> [REVIEW] CMake: Fix Arrow and GTest library paths

src/join/joining.cu, src/quantiles.cu, src/sqls_ops.cu, src/streamcompactionops.cu, src/tests/join/join-tests.cu, src/tests/quantiles/quant_tester.cu, src/tests/sqls/sqls_g_tester.cu
GDF_VALIDITY_UNSUPPORTED is returned when a function expected to work
with valid masks does not do so.
=> [REVIEW] Report error for unsupported valid masks

src/io/csv/csv-reader.cu
Currently, the csv reader is not able to detect either the `\r` or the `\n` for Windows termination of rows. 
The following PR corrects this.
=> [REVIEW] Add support for windows files that are terminated with \r\n

include/gdf/utils.h
The build (of blazingdb/master) is currently broken because of bug #176 . So PR'ing a quick fix for it.
@felipeblazing : FYI.
By the way - I have to say I'm not particularly fond of the name of this function, nor is it clear to me whether or not it should be "exposed" like this under `include/gdf` - but I'm not getting into that with the fix, I'm just getting the repository to build.
=> [REVIEW] Make gdf_is_valid inline rather than static (Fix #176)

src/join/joining.cu
Fixes [pygdf#281](https://github.com/rapidsai/pygdf/issues/281)
In the process of creating the complete dataframe while joining three gdf_tables were instantiated :
1. Left columns that are not joined on.
2. Common columns that are joined on.
3. Right columns that are not joined on.
This fix instantiates 1 or 3 only if the number of columns in the table are non zero and calls gather.
=> [REVIEW] Avoid empty gdf_table creation in joins

src/join/joining.cu
Prior to this fix, dataframe creation was done by calling gather on the left indices result of the join. This was a problem for full join because elements from the right set of columns would never be gathered into the final dataframe.
This fix calls gather on the right indices of the full join result.
=> Fix dataframe composition in full joins
